name: 'go-api'

services:
  database:
    build:
      context: .
      dockerfile: ./build/database/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-database
    container_name: ${COMPOSE_PROJECT_NAME}-database
    restart: always
    volumes:
      - type: volume
        source: database
        target: /data/db
    ports:
      - "27017:27017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    networks:
      - go-api-network
  golang:
    build:
      context: .
      dockerfile: ./build/go/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}-golang
    container_name: ${COMPOSE_PROJECT_NAME}-golang
    restart: always
    command: sh -c "go mod tidy && cd src/ && go install github.com/swaggo/swag/cmd/swag@latest && go get -u github.com/swaggo/swag/cmd/swag && swag init -g main.go -o docs && gow run main.go"
    volumes:
      - type: bind
        source: .
        target: /app/
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - database
    networks:
      - go-api-network
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=${DB_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${DB_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - database
    networks:
      - go-api-network

volumes:
  database:
    name: ${COMPOSE_PROJECT_NAME}-database

networks:
  go-api-network:
    name: ${COMPOSE_PROJECT_NAME}-network
    driver: bridge